iter = 0;
if (Meteor.isServer){
    Meteor.startup(function(){
        if (Sentences.find().count() === 0) {


            console.log ("Adding sentences to DB...");

            var trainingSentences = [
                { number: iter++,
                    text: "bad",
                    display_text: "<b style='color:blue'>bad</b>",
                    phon_transcription: "b b_ a: d d_",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "2",
                    focus_word: "bad",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "vater",
                    display_text: "<b style='color:blue'>vater</b>",
                    phon_transcription: "f a: t t_ er",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "1",
                    focus_word: "vater",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "adam",
                    display_text: "<b style='color:blue'>adam</b>",
                    phon_transcription: "Q Q_ a: d d_ a m",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "2",
                    focus_word: "adam",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "tiger",
                    display_text: "<b style='color:blue'>tiger</b>",
                    phon_transcription: "t t_ i: g g_ er",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "2",
                    focus_word: "tiger",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "sie",
                    display_text: "<b style='color:blue'>sie</b>",
                    phon_transcription: "z i:",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "1",
                    focus_word: "sie",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "sieben",
                    display_text: "<b style='color:blue'>sieben</b>",
                    phon_transcription: "z i: b b_ @ n",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "1",
                    focus_word: "sieben",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "du",
                    display_text: "<b style='color:blue'>du</b>",
                    phon_transcription: "d d_ u:",
                    focus_vowel: "u:",
                    nearby_vowel: "y:",
                    focus_Vow_Num: "2",
                    focus_word: "du",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "buch",
                    display_text: "<b style='color:blue'>buch</b>",
                    phon_transcription: "b b_ u: x",
                    focus_vowel: "u:",
                    nearby_vowel: "y:",
                    focus_Vow_Num: "2",
                    focus_word: "buch",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "mut",
                    display_text: "<b style='color:blue'>mut</b>",
                    phon_transcription: "m u: t",
                    focus_vowel: "u:",
                    nearby_vowel: "y:",
                    focus_Vow_Num: "1",
                    focus_word: "mut",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "bieten",
                    display_text: "<b style='color:blue'>bieten</b>",
                    phon_transcription: "b b_ i: t t_ @ n",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "2",
                    focus_word: "bieten",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "bitten",
                    display_text: "<b style='color:blue'>bitten</b>",
                    phon_transcription: "b b_ I t t_ @ n",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "2",
                    focus_word: "bitten",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "findet",
                    display_text: "<b style='color:blue'>findet</b>",
                    phon_transcription: "f I n d d_ @ t t_",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "1",
                    focus_word: "findet",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "fieber",
                    display_text: "<b style='color:blue'>fieber</b>",
                    phon_transcription: "f i: b b_ er",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "1",
                    focus_word: "fieber",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "das dach ist schief",
                    display_text: "das dach ist <b style='color:blue'>schief</b>",
                    phon_transcription: "d d_ a s d d_ a x Q Q_ I s t t_ S i: f",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "15",
                    focus_word: "schief",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "ich reise mit dem schiff",
                    display_text: "ich reise mit dem <b style='color:blue'>schiff</b>",
                    phon_transcription: "Q Q_ I C r aI z @ m I t t_ d d_ e: m S I f",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "17",
                    focus_word: "schiff",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "die",
                    display_text: "<b style='color:blue'>die</b>",
                    phon_transcription: "d d_ i:",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "2",
                    focus_word: "die",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "licht",
                    display_text: "<b style='color:blue'>licht</b>",
                    phon_transcription: "l I C t t_",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "1",
                    focus_word: "licht",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "ich bring dir die tasse",
                    display_text: "ich <b style='color:blue'>bring</b> dir die tasse",
                    phon_transcription: "Q Q_ I C b b_ r I N d d_ i:er d d_ i: t t_ a s @",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "7",
                    focus_word: "bring",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "ist wieder montag",
                    display_text: "ist <b style='color:blue'>wieder</b> montag?",
                    phon_transcription: "Q Q_ I s t t_ v i: d d_ er o: n t t_ a: k k_",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "7",
                    focus_word: "wieder",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "kinder spielen im park",
                    display_text: "<b style='color:blue'>kinder</b> spielen im park",
                    phon_transcription: "k k_ I n d d_ er S p p_ i: l @ n Q Q_ I m p p_ a r k k_",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "2",
                    focus_word: "kinder",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "berlin ist schön im herbst",
                    display_text: "<b style='color:blue'>berlin</b> ist schön im herbst",
                    phon_transcription: "b b_ Eer l i: n Q Q_ I s t t_ S eu: n Q Q_ I m h E r p p_ s t",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "4",
                    focus_word: "berlin",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "Schoß",
                    display_text: "<b style='color:blue'>Schoß</b>",
                    phon_transcription: "S O s",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "1",
                    focus_word: "Schoß",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "schoss",
                    display_text: "<b style='color:blue'>schoss</b>",
                    phon_transcription: "S o: s",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "1",
                    focus_word: "schoss",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "wir wohnen in ulm",
                    display_text: "wir <b style='color:blue'>wohnen</b> in Ulm",
                    phon_transcription: "v i:er V o: n @ n Q Q_ I n",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "3",
                    focus_word: "wohnen",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "die sonne scheint",
                    display_text: "die <b style='color:blue'>sonne</b> scheint",
                    phon_transcription: "d d_ i: z O n @ S aI n t t_",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "4",
                    focus_word: "sonne",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "das boot ist aus holz",
                    display_text: "das <b style='color:blue'>boot</b> ist aus holz",
                    phon_transcription: "d d_ a s b b_ o: t t_ Q Q_ I s t t_ Q Q_ aU s h O l ts ts_",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "6",
                    focus_word: "boot",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "er bot mir fünf euro",
                    display_text: "er <b style='color:blue'>bot</b> mir fünf euro",
                    phon_transcription: "Q Q_ e:er b b_ O t t_ m i: er f Y n f",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "5",
                    focus_word: "bot",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "von",
                    display_text: "<b style='color:blue'>von</b>",
                    phon_transcription: "f O n",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "1",
                    focus_word: "von",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "boden",
                    display_text: "<b style='color:blue'>boden</b>",
                    phon_transcription: "b b_ o: d d_ @ n",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "2",
                    focus_word: "boden",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "der stürmer schießt ein tor",
                    display_text: "der stürmer schießt ein <b style='color:blue'>tor</b>",
                    phon_transcription: "d d_ e:er S t t_ Y r m @ S i: s t t_ Q Q_ aI n t t_ o: r",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "21",
                    focus_word: "tor",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "die packung ist noch voll",
                    display_text: "die packung ist noch <b style='color:blue'>voll</b>",
                    phon_transcription: "d d_ i: p a k k_ U N Q Q_ I s t t_ n O x f O l",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "16, 19",
                    focus_word: "voll",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "bock",
                    display_text: "<b style='color:blue'>bock</b>",
                    phon_transcription: "b b_ O k k_",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "2",
                    focus_word: "bock",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "brot",
                    display_text: "<b style='color:blue'>brot</b>",
                    phon_transcription: "b b_ r o: t t_",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "3",
                    focus_word: "brot",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "bahn",
                    display_text: "<b style='color:blue'>bahn</b>",
                    phon_transcription: "b b_ a: n",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "2",
                    focus_word: "bahn",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "bann",
                    display_text: "<b style='color:blue'>bann</b>",
                    phon_transcription: "b b_ a n",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "2",
                    focus_word: "bann",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "hat",
                    display_text: "<b style='color:blue'>hat</b>",
                    phon_transcription: "h a t t_",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "1",
                    focus_word: "hat",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "nach",
                    display_text: "<b style='color:blue'>nach</b>",
                    phon_transcription: "n a: x",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "1",
                    focus_word: "nach",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "die jacke hängt am haken",
                    display_text: "die jacke hängt am <b style='color:blue'>haken</b>",
                    phon_transcription: "d d_ i: j a k k_ @ h E N t t_ Q Q_ a m h a: k k_ @ n",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "18",
                    focus_word: "haken",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "das holz muss man hacken",
                    display_text: "das holz muss man <b style='color:blue'>hacken</b>",
                    phon_transcription: "d d_ a s h O l ts ts_ m U s m a n h a k k_ @ n",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "16",
                    focus_word: "hacken",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "das ist deine wahl",
                    display_text: "das ist deine <b style='color:blue'>wahl</b>",
                    phon_transcription: "d d_ a s Q Q_ I s t t_ d d_ aI n @ v a: l",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "16",
                    focus_word: "wahl",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "das ist eine dunkle gasse",
                    display_text: "das ist eine dunkle <b style='color:blue'>gasse</b>",
                    phon_transcription: "d d_ a s Q Q_ I s t t_ Q Q_ aI n @ d d_ U N k k_ l @ g g_ a s @",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "25",
                    focus_word: "gasse",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "abend",
                    display_text: "<b style='color:blue'>abend</b>",
                    phon_transcription: "Q Q_ a: b b_ @ n t t_",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "2",
                    focus_word: "abend",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "nacht",
                    display_text: "<b style='color:blue'>nacht</b>",
                    phon_transcription: "n a x t t_",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "1",
                    focus_word: "nacht",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "ich schaue heute tatort",
                    display_text: "ich schaue heute <b style='color:blue'>tatort</b>",
                    phon_transcription: "Q Q_ I C S aU @ h OY t t_ @ t t_ a: t t_ Q Q_ Oer t t_",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "14",
                    focus_word: "tatort",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "ich bezahle an der kasse",
                    display_text: "ich bezahle an der <b style='color:blue'>kasse</b>",
                    phon_transcription: "Q Q_ I C b b_ @ ts a: l @ Q Q_ a n d d_ e:er k k_ a s @",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "13, 20",
                    focus_word: "kasse",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "miete",
                    display_text: "<b style='color:blue'>miete</b>",
                    phon_transcription: "m i: t t_ @",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "1",
                    focus_word: "miete",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "mitte",
                    display_text: "<b style='color:blue'>mitte</b>",
                    phon_transcription: "m I t t_ @",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "1",
                    focus_word: "mitte",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "wie",
                    display_text: "<b style='color:blue'>wie</b>",
                    phon_transcription: "v i:",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "1",
                    focus_word: "wie",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "mit",
                    display_text: "<b style='color:blue'>mit</b>",
                    phon_transcription: "m I t t_",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "1",
                    focus_word: "mit",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "die letzte nacht war still",
                    display_text: "die letzte nacht war <b style='color:blue'>still</b>",
                    phon_transcription: "d d_ i: l E ts ts_ t t_ @ n a x t t_ v a:er S t t_ I l",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "20",
                    focus_word: "still",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "ich esse ein eis am stiel",
                    display_text: "ich esse ein eis am <b style='color:blue'>stiel</b>",
                    phon_transcription: "Q Q_ I C Q Q_ E s @ Q Q_ aI n Q Q_ aI s Q Q_ a m S t t_ i: l",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "24",
                    focus_word: "stiel",
                    focus_word_Num: "5" },

                { number: iter++,
                    text: "ich bin ein sieger",
                    display_text: "ich bin ein <b style='color:blue'>sieger</b>",
                    phon_transcription: "Q Q_ I C b b_ I n Q Q_ aI n z i: g g_ er",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "13",
                    focus_word: "sieger",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "ich lese häufig",
                    display_text: "ich lese <b style='color:blue'>häufig</b>",
                    phon_transcription: "Q Q_ I C l e: z @ h OY f I C",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "11",
                    focus_word: "häufig",
                    focus_word_Num: "2" },

                { number: iter++,
                    text: "bist du im kino",
                    display_text: "bist du <b style='color:blue'>im</b> kino?",
                    phon_transcription: "b b_ I s t t_ d d_ u: Q Q_ I m k_ i: n o",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "11",
                    focus_word: "im",
                    focus_word_Num: "2" },

                { number: iter++,
                    text: "hast du ihm gesagt",
                    display_text: "hast du <b style='color:blue'>ihm</b> gesagt...?",
                    phon_transcription: "h a s t t_ d d_ u: Q Q_ i: m",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "10",
                    focus_word: "ihm",
                    focus_word_Num: "2" },

                { number: iter++,
                    text: "email",
                    display_text: "<b style='color:blue'>email</b>",
                    phon_transcription: "Q Q_ i: m eI l",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "2",
                    focus_word: "email",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "sind",
                    display_text: "<b style='color:blue'>sind</b>",
                    phon_transcription: "z I n t t_",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "1",
                    focus_word: "sind",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "der fels hat risse",
                    display_text: "der fels hat <b style='color:blue'>risse</b>",
                    phon_transcription: "d d_ e:er f E l s h a t t_ r I s @",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "12",
                    focus_word: "risse",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "der mann ist ein riese",
                    display_text: "der mann ist ein <b style='color:blue'>riese</b>",
                    phon_transcription: "d d_ e:er m a n Q Q_ I s t t_ Q Q_ aI n r i: s @",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "17",
                    focus_word: "riese",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "ich habe schmerzen am knie",
                    display_text: "ich habe schmerzen am <b style='color:blue'>knie</b>",
                    phon_transcription: "Q Q_ I C h a: b b_ @ S m Eer ts ts_ @ n Q Q_ a m k k_ n i:",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "23",
                    focus_word: "knie",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "ich schicke einen brief an dich",
                    display_text: "ich schicke einen brief an <b style='color:blue'>dich</b>",
                    phon_transcription: "Q Q_ I C S I k k_ @ Q Q_ aI n @ n b b_ r i: f Q Q_ a n d d_ I C",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "26",
                    focus_word: "dich",
                    focus_word_Num: "5" },

                { number: iter++,
                    text: "schiss",
                    display_text: "<b style='color:blue'>schiss</b>",
                    phon_transcription: "] S I s",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "2",
                    focus_word: "schiss",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "schieß",
                    display_text: "<b style='color:blue'>schieß</b>",
                    phon_transcription: "S i: s",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "1",
                    focus_word: "schieß",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "kiefer",
                    display_text: "<b style='color:blue'>kiefer</b>",
                    phon_transcription: "k k_ i: f er",
                    focus_vowel: "i:",
                    nearby_vowel: "I",
                    focus_Vow_Num: "2",
                    focus_word: "kiefer",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "kiffer",
                    display_text: "<b style='color:blue'>kiffer</b>",
                    phon_transcription: "k k_ I f er",
                    focus_vowel: "I",
                    nearby_vowel: "i:",
                    focus_Vow_Num: "2",
                    focus_word: "kiffer",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "ofen",
                    display_text: "<b style='color:blue'>ofen</b>",
                    phon_transcription: "Q Q_ o: f n",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "2",
                    focus_word: "ofen",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "offen",
                    display_text: "<b style='color:blue'>offen</b>",
                    phon_transcription: "Q Q_ O f n",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "2",
                    focus_word: "offen",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "auto",
                    display_text: "<b style='color:blue'>auto</b>",
                    phon_transcription: "Q Q_ aU t t_ o:",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "5",
                    focus_word: "auto",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "block",
                    display_text: "<b style='color:blue'>block</b>",
                    phon_transcription: "b b_ l O k k_",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "3",
                    focus_word: "block",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "polen ist ein schönes land",
                    display_text: "<b style='color:blue'>polen</b> ist ein schönes land",
                    phon_transcription: "p p_ o: l @ n Q Q_ I s t t_ Q Q_ aI n S eu: n @ s l a n t t_",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "2",
                    focus_word: "polen",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "pollen fliegen durch die luft",
                    display_text: "<b style='color:blue'>pollen</b> fliegen durch die luft",
                    phon_transcription: "p p_ O l @ n f l i: g g_ @ n d d_ Uer C d d_ i: l U f t t_",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "2",
                    focus_word: "pollen",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "meine socken sind nass",
                    display_text: "meine <b style='color:blue'>socken</b> sind nass",
                    phon_transcription: "m aI n @ z O k k_ @ n z I n t t_ n a s",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "5",
                    focus_word: "socken",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "die metro ist voll",
                    display_text: "die <b style='color:blue'>metro</b> ist voll",
                    phon_transcription: "d d_ i: m e: t t_ r o: Q Q_ I s t t_ f O l",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "8",
                    focus_word: "metro",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "er schießt mit schrot",
                    display_text: "er schießt mit <b style='color:blue'>schrot</b>",
                    phon_transcription: "Q Q_ e:er S i: s t t_ m I t t_ S r o: t t_",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "14",
                    focus_word: "schrot",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "mein auto ist schrott",
                    display_text: "mein auto ist <b style='color:blue'>schrott</b>",
                    phon_transcription: "m aI n Q Q_ aU t t_ o: Q Q_ I s t t_ S r O t t_",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "17",
                    focus_word: "schrott",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "oder",
                    display_text: "<b style='color:blue'>oder</b>",
                    phon_transcription: "Q Q_ o: d d_ er",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "2",
                    focus_word: "oder",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "tonne",
                    display_text: "<b style='color:blue'>tonne</b>",
                    phon_transcription: "t t_ O n @",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "2",
                    focus_word: "tonne",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "richter tragen roben",
                    display_text: "richter tragen <b style='color:blue'>roben</b>",
                    phon_transcription: "r I C t t_ er t t_ r a: g g_ @ n r o: b b_ @ n",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "15",
                    focus_word: "roben",
                    focus_word_Num: "2" },

                { number: iter++,
                    text: "in Alaska leben robben",
                    display_text: "in Alaska leben <b style='color:blue'>robben</b>",
                    phon_transcription: "Q Q_ I n l e: b b_ n r O b b_ @ n",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "10",
                    focus_word: "robben",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "hohl",
                    display_text: "<b style='color:blue'>hohl</b>",
                    phon_transcription: "h o: l",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "1",
                    focus_word: "hohl",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "hol",
                    display_text: "<b style='color:blue'>hol</b>",
                    phon_transcription: "h O l",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "1",
                    focus_word: "hol",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "rogen",
                    display_text: "<b style='color:blue'>rogen</b>",
                    phon_transcription: "r o: g g_ n",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "1",
                    focus_word: "rogen",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "roggen",
                    display_text: "<b style='color:blue'>roggen</b>",
                    phon_transcription: "r O g g_ n",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "1",
                    focus_word: "roggen",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "das seil hat einen knoten",
                    display_text: "das seil hat einen <b style='color:blue'>knoten</b>",
                    phon_transcription: "d d_ a s z ai l h a t t_ Q Q_ aI n @ n k k_ n o: t t_ @ n",
                    focus_vowel: "o:",
                    nearby_vowel: "O",
                    focus_Vow_Num: "20",
                    focus_word: "knoten",
                    focus_word_Num: "4" },

                { number: iter++,
                    text: "ich backe eine torte",
                    display_text: "ich backe eine <b style='color:blue'>torte</b>",
                    phon_transcription: "Q Q_ I C b b_ a k k_ @ Q Q_ aI n @ t t_ O r t @",
                    focus_vowel: "O",
                    nearby_vowel: "o:",
                    focus_Vow_Num: "17",
                    focus_word: "torte",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "die hasen springen weg",
                    display_text: "die <b style='color:blue'>hasen</b> springen weg",
                    phon_transcription: "d d_ i: h a: z @ n S p p_ r I N @ n v E k k_",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "4",
                    focus_word: "hasen",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "sie hassen meine oma",
                    display_text: "sie <b style='color:blue'>hassen</b> meine oma",
                    phon_transcription: "z i: h a s @ n m aI n @ Q Q_ o: m a",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "3",
                    focus_word: "hassen",
                    focus_word_Num: "1" },

                { number: iter++,
                    text: "wir müssen schnell fahren",
                    display_text: "wir müssen schnell <b style='color:blue'>fahren</b>",
                    phon_transcription: "v i:er m Y s n S n E l f a: r @ n",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "11",
                    focus_word: "fahren",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "heute werde ich zwanzig",
                    display_text: "heute werde ich <b style='color:blue'>zwanzig</b>",
                    phon_transcription: "h OY t t_ @ v e: er d d_ @ Q Q_ I C ts ts_ v a n ts ts_ I C",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "18",
                    focus_word: "zwanzig",
                    focus_word_Num: "3" },

                { number: iter++,
                    text: "stadt",
                    display_text: "<b style='color:blue'>stadt</b>",
                    phon_transcription: "S t t_ a t t_",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "3",
                    focus_word: "stadt",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "staat",
                    display_text: "<b style='color:blue'>staat</b>",
                    phon_transcription: "S t t_ a: t t_",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "3",
                    focus_word: "staat",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "rad",
                    display_text: "<b style='color:blue'>rad</b>",
                    phon_transcription: "r a: t t_",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "1",
                    focus_word: "rad",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "kann",
                    display_text: "<b style='color:blue'>kann</b>",
                    phon_transcription: "k k_ a n",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "2",
                    focus_word: "kann",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "ratten sind eklig",
                    display_text: "<b style='color:blue'>ratten</b> sind eklig",
                    phon_transcription: "r a t t_ n z I n t t_ Q Q_ e: k k_ l I C",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "1",
                    focus_word: "ratten",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "raten ist erlaubt",
                    display_text: "<b style='color:blue'>raten</b> ist erlaubt",
                    phon_transcription: "r a: t t_ n Q Q_ I s t t_ Q Q_ e: er l a p p_ t t_",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "1",
                    focus_word: "raten",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "haben",
                    display_text: "<b style='color:blue'>haben</b>",
                    phon_transcription: "h a: b b_ @ n",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "1",
                    focus_word: "haben",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "katze",
                    display_text: "<b style='color:blue'>katze</b>",
                    phon_transcription: "k k_ a ts ts_ @",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "2",
                    focus_word: "katze",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "wahn",
                    display_text: "<b style='color:blue'>wahn</b>",
                    phon_transcription: "v a: n",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "1",
                    focus_word: "wahn",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "wann",
                    display_text: "<b style='color:blue'>wann</b>",
                    phon_transcription: "v a n",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "1",
                    focus_word: "wann",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "kam",
                    display_text: "<b style='color:blue'>kam</b>",
                    phon_transcription: "k k_ a: m",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "2",
                    focus_word: "kam",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "kamm",
                    display_text: "<b style='color:blue'>kamm</b>",
                    phon_transcription: "k k_ a m",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "2",
                    focus_word: "kamm",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "man muss bezahlen",
                    display_text: "<b style='color:blue'>man</b> muss bezahlen",
                    phon_transcription: "m a n m U s b b_ @ ts a: l @ n",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "1",
                    focus_word: "man",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "gas ist brenbar",
                    display_text: "<b style='color:blue'>gas</b> ist brenbar",
                    phon_transcription: "g g_ a: s Q Q_ I s t t_ b b_ r E n b b_ a:er",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "2",
                    focus_word: "gas",
                    focus_word_Num: "0" },

                { number: iter++,
                    text: "ich habe eine blase am fuß",
                    display_text: "ich habe eine <b style='color:blue'>blase</b> am fuß",
                    phon_transcription: "Q Q_ I C h a: b b_ @ Q Q_ aI n @b b_ l a: s @ Q Q_ a m f u: s",
                    focus_vowel: "a:",
                    nearby_vowel: "a",
                    focus_Vow_Num: "16",
                    focus_word: "blase",
                    focus_word_Num: "3" },


                { number: iter++,
                    text: "sie hat eine blasse haut",
                    display_text: "sie hat eine <b style='color:blue'>blasse</b> haut",
                    phon_transcription: "z i: h a t t_ Q Q_ aI n @b b_ l a s @ h aU t t_",
                    focus_vowel: "a",
                    nearby_vowel: "a:",
                    focus_Vow_Num: "13",
                    focus_word: "blasse",
                    focus_word_Num: "3" }

        ];



            _.each(trainingSentences, function(entry){
                var fs = Npm.require('fs');
                var path = process.env.PWD + "/public/Sentences/";
                //console.log("Path is:" + path);
                fs.writeFile(path + "sentence" + entry.number + ".txt", entry.text,
                    function(err){
                        if (err) throw err;
                        console.log('saved ' + "sentence" + entry.number + ".txt to file system");

                });
                Sentences.insert(entry);
            });
            console.log("finished inserting sentences in DB...");
            //console.log(JSON.stringify(trainingSentences));
        }
    })
}


